In [1]:
import numpy as np
import pandas as pd

1. Count

In [2]:
pd.read_csv('kohli_ipl.csv')

     match_no  runs
0           1     1
1           2    23
2           3    13
3           4    12
4           5     1
..        ...   ...
210       211     0
211       212    20
212       213    73
213       214    25
214       215     7

[215 rows x 2 columns]

In [8]:
vk =pd.read_csv('kohli_ipl.csv',index_col='match_no').squeeze().sort_values(ascending=True)
vk

match_no
8        0
87       0
93       0
91       0
206      0
      ...
164    100
120    100
123    108
126    109
128    113
Name: runs, Length: 215, dtype: int64

In [26]:
#indexing
movies =pd.read_csv('bollywood.csv',index_col='movie').squeeze()
movies

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

In [10]:
print(vk.count())

215

2. Sum -> product

In [20]:
subs = pd.read_csv('subs.csv')
subs.sort_values(by='Subscribers gained', ascending=True)

     Subscribers gained
42                   33
6                    33
24                   35
19                   37
14                   39
..                  ...
280                 295
233                 301
168                 306
331                 312
330                 396

[365 rows x 1 columns]

In [21]:
subs.sum()

Subscribers gained    49510
dtype: int64

In [22]:
subs.product()

Subscribers gained    0
dtype: int64

mean->median->mode->std->var

In [31]:
subs.mean()
print(vk.median())
print(movies.mode())# will show the actor name with highest number of movies
print(subs.std())#standard deviation
print(vk.var())#variance

24.0
0    Akshay Kumar
Name: lead, dtype: object
Subscribers gained    62.675023
dtype: float64
688.0024777222343

min/max

In [32]:
subs.min()

Subscribers gained    33
dtype: int64

In [33]:
subs.max()

Subscribers gained    396
dtype: int64

Describe

In [34]:
vk.describe()

count    215.000000
mean      30.855814
std       26.229801
min        0.000000
25%        9.000000
50%       24.000000
75%       48.000000
max      113.000000
Name: runs, dtype: float64