In [1]:
import numpy as np
import pandas as pd

In [2]:
movies = pd.read_csv('../dataSets/imdb-top-1000.csv')
movies

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
0,The Shawshank Redemption,1994,142,Drama,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
1,The Godfather,1972,175,Crime,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
3,The Godfather: Part II,1974,202,Crime,9.0,Francis Ford Coppola,Al Pacino,1129952,57300000.0,90.0
4,12 Angry Men,1957,96,Crime,9.0,Sidney Lumet,Henry Fonda,689845,4360000.0,96.0
...,...,...,...,...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,115,Comedy,7.6,Blake Edwards,Audrey Hepburn,166544,679874270.0,76.0
996,Giant,1956,201,Drama,7.6,George Stevens,Elizabeth Taylor,34075,195217415.0,84.0
997,From Here to Eternity,1953,118,Drama,7.6,Fred Zinnemann,Burt Lancaster,43374,30500000.0,85.0
998,Lifeboat,1944,97,Drama,7.6,Alfred Hitchcock,Tallulah Bankhead,26471,852142728.0,78.0
999,The 39 Steps,1935,86,Crime,7.6,Alfred Hitchcock,Robert Donat,51853,302787539.0,93.0

In [3]:
genres = movies.groupby('Genre')
genres.first()

,Series_Title,Released_Year,Runtime,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
Genre,,,,,,,,,
Action,The Dark Knight,2008,152,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
Adventure,Interstellar,2014,169,8.6,Christopher Nolan,Matthew McConaughey,1512360,188020017.0,74.0
Animation,Sen to Chihiro no kamikakushi,2001,125,8.6,Hayao Miyazaki,Daveigh Chase,651376,10055859.0,96.0
Biography,Schindler's List,1993,195,8.9,Steven Spielberg,Liam Neeson,1213505,96898818.0,94.0
Comedy,Gisaengchung,2019,132,8.6,Bong Joon Ho,Kang-ho Song,552778,53367844.0,96.0
Crime,The Godfather,1972,175,9.2,Francis Ford Coppola,Marlon Brando,1620367,134966411.0,100.0
Drama,The Shawshank Redemption,1994,142,9.3,Frank Darabont,Tim Robbins,2343110,28341469.0,80.0
Family,E.T. the Extra-Terrestrial,1982,115,7.8,Steven Spielberg,Henry Thomas,372490,435110554.0,91.0
Fantasy,Das Cabinet des Dr. Caligari,1920,76,8.1,Robert Wiene,Werner Krauss,57428,337574718.0,NaN
Film-Noir,The Third Man,1949,104,8.1,Carol Reed,Orson Welles,158731,449191.0,97.0
Horror,Psycho,1960,109,8.5,Alfred Hitchcock,Anthony Perkins,604211,32000000.0,97.0
Mystery,Memento,2000,113,8.4,Christopher Nolan,Guy Pearce,1125712,25544867.0,80.0
Thriller,Wait Until Dark,1967,108,7.8,Terence Young,Audrey Hepburn,27733,17550741.0,81.0
Western,"Il buono, il brutto, il cattivo",1966,161,8.8,Sergio Leone,Clint Eastwood,688390,6100000.0,90.0

In [5]:
duo=movies.groupby(['Director','Star1'])
duo

In [7]:

duo.size()

Director             Star1
Aamir Khan           Amole Gupte       1
Aaron Sorkin         Eddie Redmayne    1
Abdellatif Kechiche  Léa Seydoux       1
Abhishek Chaubey     Shahid Kapoor     1
Abhishek Kapoor      Amit Sadh         1
                                      ..
Zaza Urushadze       Lembit Ulfsak     1
Zoya Akhtar          Hrithik Roshan    1
                     Vijay Varma       1
Çagan Irmak          Çetin Tekindor    1
Ömer Faruk Sorak     Cem Yilmaz        1
Length: 898, dtype: int64

In [ ]:
duo.get_group(('Christopher Nolan', 'Christian Bale'))# director actor

,Series_Title,Released_Year,Runtime,Genre,IMDB_Rating,Director,Star1,No_of_Votes,Gross,Metascore
2,The Dark Knight,2008,152,Action,9.0,Christopher Nolan,Christian Bale,2303232,534858444.0,84.0
36,The Prestige,2006,130,Drama,8.5,Christopher Nolan,Christian Bale,1190259,53089891.0,66.0
63,The Dark Knight Rises,2012,164,Action,8.4,Christopher Nolan,Christian Bale,1516346,448139099.0,78.0
155,Batman Begins,2005,140,Action,8.2,Christopher Nolan,Christian Bale,1308302,206852432.0,70.0

In [12]:
#the most earning actor director combo
duo['Gross'].sum().sort_values(ascending=False).head(1)

Director        Star1
Akira Kurosawa  Toshirô Mifune    2.999877e+09
Name: Gross, dtype: float64

In [15]:
#find the best metaScore on the basis of actor genreCombo
movies.groupby(['Star1','Genre'])['Metascore'].mean().reset_index().sort_values('Metascore',ascending=False)

                Star1      Genre  Metascore
606     Peter O'Toole  Adventure      100.0
590      Orson Welles      Drama      100.0
77        Bertil Guve      Drama      100.0
230    Ellar Coltrane      Drama      100.0
329   Humphrey Bogart      Drama      100.0
..                ...        ...        ...
807    William Holden      Drama        NaN
812           Won Bin     Action        NaN
815              Yash     Action        NaN
826    Çetin Tekindor      Drama        NaN
828  Ömer Faruk Sorak     Comedy        NaN

[829 rows x 3 columns]

In [17]:
#agg on multiple grouby
duo[['IMDB_Rating', 'Runtime', 'No_of_Votes']].agg(['min','max','mean'])

                                   IMDB_Rating           Runtime              \
                                           min  max mean     min  max   mean
Director            Star1
Aamir Khan          Amole Gupte            8.4  8.4  8.4     165  165  165.0
Aaron Sorkin        Eddie Redmayne         7.8  7.8  7.8     129  129  129.0
Abdellatif Kechiche Léa Seydoux            7.7  7.7  7.7     180  180  180.0
Abhishek Chaubey    Shahid Kapoor          7.8  7.8  7.8     148  148  148.0
Abhishek Kapoor     Amit Sadh              7.7  7.7  7.7     130  130  130.0
...                                        ...  ...  ...     ...  ...    ...
Zaza Urushadze      Lembit Ulfsak          8.2  8.2  8.2      87   87   87.0
Zoya Akhtar         Hrithik Roshan         8.1  8.1  8.1     155  155  155.0
                    Vijay Varma            8.0  8.0  8.0     154  154  154.0
Çagan Irmak         Çetin Tekindor         8.3  8.3  8.3     112  112  112.0
Ömer Faruk Sorak    Cem Yilmaz             8.0  8.0  8.0     127  127  127.0

                                   No_of_Votes
                                           min     max      mean
Director            Star1
Aamir Khan          Amole Gupte         168895  168895  168895.0
Aaron Sorkin        Eddie Redmayne       89896   89896   89896.0
Abdellatif Kechiche Léa Seydoux         138741  138741  138741.0
Abhishek Chaubey    Shahid Kapoor        27175   27175   27175.0
Abhishek Kapoor     Amit Sadh            32628   32628   32628.0
...                                        ...     ...       ...
Zaza Urushadze      Lembit Ulfsak        40382   40382   40382.0
Zoya Akhtar         Hrithik Roshan       67927   67927   67927.0
                    Vijay Varma          31886   31886   31886.0
Çagan Irmak         Çetin Tekindor       78925   78925   78925.0
Ömer Faruk Sorak    Cem Yilmaz           56960   56960   56960.0

[898 rows x 9 columns]