In [1]:
import numpy as np
import pandas as pd

In [13]:
movies =pd.read_csv('bollywood.csv',index_col='movie').squeeze()
movies

movie
Uri: The Surgical Strike                   Vicky Kaushal
Battalion 609                                Vicky Ahuja
The Accidental Prime Minister (film)         Anupam Kher
Why Cheat India                            Emraan Hashmi
Evening Shadows                         Mona Ambegaonkar
                                              ...
Hum Tumhare Hain Sanam                    Shah Rukh Khan
Aankhen (2002 film)                     Amitabh Bachchan
Saathiya (film)                             Vivek Oberoi
Company (film)                                Ajay Devgn
Awara Paagal Deewana                        Akshay Kumar
Name: lead, Length: 1500, dtype: object

In [2]:
vk =pd.read_csv('kohli_ipl.csv',index_col='match_no').squeeze().sort_values(ascending=True)
vk

match_no
8        0
87       0
93       0
91       0
206      0
      ...
164    100
120    100
123    108
126    109
128    113
Name: runs, Length: 215, dtype: int64

In [8]:
subs = pd.read_csv('subs.csv')
subs.sort_values(by='Subscribers gained', ascending=True)

     Subscribers gained
42                   33
6                    33
24                   35
19                   37
14                   39
..                  ...
280                 295
233                 301
168                 306
331                 312
330                 396

[365 rows x 1 columns]

BOOLEAN INDEXING ON SERIES

In [3]:
vk[vk>=50]

match_no
15      50
182     50
197     51
71      51
103     51
122     52
198     53
131     54
129     54
137     55
44      56
85      56
144     57
57      57
80      57
34      58
209     58
141     58
73      58
104     62
132     62
134     64
74      65
45      67
162     67
97      67
148     68
52      70
152     70
41      71
175     72
188     72
68      73
213     73
99      73
127     75
116     75
117     79
119     80
110     82
160     84
178     90
145     92
81      93
82      99
164    100
120    100
123    108
126    109
128    113
Name: runs, dtype: int64

In [ ]:
#size

In [4]:
vk[vk>=50].size

50

In [5]:
#find the number of ducks
vk==0

match_no
8       True
87      True
93      True
91      True
206     True
       ...
164    False
120    False
123    False
126    False
128    False
Name: runs, Length: 215, dtype: bool

In [6]:
vk[vk==0]

match_no
8      0
87     0
93     0
91     0
206    0
207    0
135    0
130    0
211    0
Name: runs, dtype: int64

In [7]:
vk[vk==0].size

9

In [ ]:
#Count number of day when 1 had more than 200 subs a day

In [10]:
subs[subs>200]

     Subscribers gained
0                   NaN
1                   NaN
2                   NaN
3                   NaN
4                   NaN
..                  ...
360               231.0
361               226.0
362                 NaN
363                 NaN
364                 NaN

[365 rows x 1 columns]

In [ ]:
#Count the no. of Days when I had more than 200 subscriber a day
subs[subs>200].size

365

In [22]:
# find actors who have done more than 20 movies
num_movies = movies.value_counts() # gives the count of movies each actor has done
num_movies

lead
Akshay Kumar            48
Amitabh Bachchan        45
Ajay Devgn              38
Salman Khan             31
Sanjay Dutt             26
                        ..
Tanishaa Mukerji         1
Tanuja                   1
Ankit                    1
Rakhee Gulzar            1
Geetika Vidya Ohlyan     1
Name: count, Length: 566, dtype: int64

In [23]:
num_movies[num_movies>20]

lead
Akshay Kumar        48
Amitabh Bachchan    45
Ajay Devgn          38
Salman Khan         31
Sanjay Dutt         26
Shah Rukh Khan      22
Emraan Hashmi       21
Name: count, dtype: int64